### ISSUE TITLE
Include Word count for the options.

### ISSUE THREAD

**Issue by Raj4everr** [dipendrapkrl/TriviaHelper#18]
Are you On a leave bro??? nothing new from your side in the app for accuracy...hope everything's fine...fingers crossed...well try if U can to show seperately...number of times each word occurs...

**Comment by Kartkprajapat** [comment]
100% agreed

**Comment by dipendrapkrl** [comment]
I was in vacation. Update is on the way.

**Comment by Raj4everr** [comment]
Good to hear that you are well and doing fine...bro this update has good
accuracy...but some times it most of the time it shows "time out error" and
sometimes it takes "more than 10 seconds to show the answer"...also when
playing "cash show" we need to give answers within 5 seconds...

**Comment by Raj4everr** [comment]
Bro "trivia help" app shows "answers" in an instant...see if u can find out
how it does...then maybe it could help in "trivia helper"...
