### ISSUE TITLE
Other Apps

### ISSUE THREAD

**Issue by Bradfion95** [dipendrapkrl/TriviaHelper#20]
Can you make it for k.o. trivia , cashshow, hangtime, the q and swagiq.

**Comment by dipendrapkrl** [comment]
Post their screenshots please. I can see what I could do

**Comment by dipendrapkrl** [comment]
It works for cash show btw. Select multiple block in cropping.

**Comment by Bradfion95** [comment]
![screenshot_20180619-123147_ko trivia](https://user-images.githubusercontent.com/40159505/41746672-3ef394b0-7579-11e8-9961-8cbc8931337b.jpg)
![screenshot_20180619-200643_cash show](https://user-images.githubusercontent.com/40159505/41746683-49e81bd4-7579-11e8-9f1c-bc82ae717980.jpg)
![screenshot_20180619-203937_the question](https://user-images.githubusercontent.com/40159505/41746704-5bdeef8e-7579-11e8-97e1-e53e95ba8876.jpg)
![screenshot_20180619-201123_swagiq](https://user-images.githubusercontent.com/40159505/41746716-68e60776-7579-11e8-803d-b4482b054ce8.jpg)

**Comment by Bradfion95** [comment]
When is the next update coming?

**Comment by dipendrapkrl** [comment]
The app should work with all of them out of the box.
Create separate profile for each of them. Let me know

**Comment by dipendrapkrl** [comment]
Closing this as this is already supported by app out of the box
