### ISSUE TITLE
Correct incorrect type questions

### ISSUE THREAD

**Issue by Raj4everr** [dipendrapkrl/TriviaHelper#21]
[
![screenshot_20180625-204230](https://user-images.githubusercontent.com/40124842/41859555-09358bfa-78ba-11e8-9b17-262fcc6238ed.png)
](url)
![screenshot_20180625-204224](https://user-images.githubusercontent.com/40124842/41859631-32eec81c-78ba-11e8-93ae-6b88d7f38db5.png)
Can you do something about these types of questions....always answers shown by the app is wrong...

**Comment by dipendrapkrl** [comment]
That seems complicated. I will see if I can do anything
