### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by Raj4everr** [dipendrapkrl/TriviaHelper#24]
![screenshot_20180702-195147](https://user-images.githubusercontent.com/40124842/42169487-810f54fe-7e31-11e8-8fc2-61f523065d73.png)
Can the preview of the first page of Google search be shown on screen...sometimes answers differ due to word count...

**Comment by dipendrapkrl** [comment]
Its doable but I do not think it necessary increase accuracy overall.
