### ISSUE TITLE
Add ability to position floating view at the bottom with ease.

### ISSUE THREAD

**Issue by dipendrapkrl** [dipendrapkrl/TriviaHelper#3]
Currently when I try to position floating view to the bottom, it tries to be collected by trash can. 
It would be better if I could place at the bottom with more ease.
Suggestion: Remove Trash can and  make it close when notification is clicked.

**Comment by anilgavare** [comment]
sir giving ruler scale facility to crop question and answer perfectly

**Comment by dipendrapkrl** [comment]
@anilgavare please create another issue with more description. This is related to floating view.

**Comment by dipendrapkrl** [comment]
Feature added
