### ISSUE TITLE
The Q game

### ISSUE THREAD

**Issue by pabloavegno** [dipendrapkrl/TriviaHelper#40]
It does not recognize question and answers.
It's not as important as others but would be nice to include as supported.
As you can see in 2 attached images, the question can be with different heights

![screenshot_20180711-214108](https://user-images.githubusercontent.com/40970694/42630552-8312a002-85ad-11e8-8cd1-61f6bbf907a4.png)
![screenshot_20180711-214146](https://user-images.githubusercontent.com/40970694/42630553-83584f30-85ad-11e8-9100-d0cb288e678c.png)

**Comment by dipendrapkrl** [comment]
@pabloavegno I am wondering why it would not be supported. While cropping, select everything as single box(including question and all options). It should work out of the box. Let me know if you had any luck.

**Comment by pabloavegno** [comment]
Perfect. With separate blocks doesn't work but with only one block it works okay. You can Close the ticket :-)

**Comment by dipendrapkrl** [comment]
Awesome. Thanks.  You can join this channel for discussions. You will be the first one though :D 
https://discordapp.com/invite/g8GxNzr
